# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'default'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'   
    
- task: CopyFiles@2
  inputs: 
    sourceFolder: \\dfs\Development\Packages\nwrfcsdk
    targetFolder: $(Build.SourcesDirectory)\nwrfcsdk
    cleanTargetFolder: true
    
- task: GitVersion@4
  displayName: 'GitVersion'
  inputs:
    updateAssemblyInfo: true
    
- task: MSBuild@1
  inputs:
    platform: x86
    configuration: Release
   
- task: MSBuild@1
  inputs:
    platform: x64
    configuration: Release    
    
- task: MSBuild@1
  inputs:
    platform: AnyCPU
    configuration: Release      

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: drop
